## **Externship Assignment - 1**

In [ ]:
Name= "K Hannah Jessica"
Age = 20
print(Name,Age)

K Hannah Jessica 20


In [ ]:
t = "Datascience is used to extract meaningful insights."

x = t.split()

print(x)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [ ]:
def multiply(a, b):
    num = (a * b)
    return num

a = 2
b = 3

product = multiply(a, b)
print("The Multiplication of two numbers is:", product)

The Multiplication of two numbers is: 6


In [ ]:
capitals = {"Bihar":"Patna", "Andhra Pradesh":"Amaravati", "Karnataka":"Bangalore", "Maharashtra":"Mumbai", "Telangana":"Hyderabad"}

for key in capitals:
    print("Key = " + key + ", Value = " + capitals[key])

Key = Bihar, Value = Patna
Key = Andhra Pradesh, Value = Amaravati
Key = Karnataka, Value = Bangalore
Key = Maharashtra, Value = Mumbai
Key = Telangana, Value = Hyderabad


In [ ]:
numberslist1=list(range(1, 1000))
print(numberslist1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [ ]:
import numpy as np

dimension = 4
identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
import numpy as np
x =  np.arange(1, 10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a = 3
b = 3

def sum(arr):
    sum = 0
    for i in range(a):
        for j in range(b):
            sum = sum + arr[i][j]
    return sum

arr = [[2, 3, 7], [1, 5, 8], [4, 6, 9]]

x = 1
for i in range(a):
    for j in range(b):
        arr[i][j] = x
        x += 1

print(sum(arr))

45


In [ ]:
from datetime import datetime
import pandas as pd

start_date = datetime.strptime("2023-02-01", "%Y-%m-%d")
end_date = datetime.strptime("2023-03-01", "%Y-%m-%d")

D = 'D'

date_list = pd.date_range(start_date, end_date, freq=D)
s = pd.Series(np.random.randn(len(date_list)), index=date_list)
print(f"Creating list of dates starting from {start_date} to {end_date}")
print(s)


Creating list of dates starting from 2023-02-01 00:00:00 to 2023-03-01 00:00:00
2023-02-01   -0.980842
2023-02-02    1.954110
2023-02-03   -1.313576
2023-02-04    1.496203
2023-02-05    1.429949
2023-02-06   -0.504699
2023-02-07    0.750034
2023-02-08   -1.074268
2023-02-09    1.449284
2023-02-10    0.075017
2023-02-11   -0.111090
2023-02-12   -0.409995
2023-02-13    1.638985
2023-02-14   -0.293298
2023-02-15   -0.827680
2023-02-16    0.610952
2023-02-17   -1.459356
2023-02-18    0.418299
2023-02-19    0.460344
2023-02-20   -1.787248
2023-02-21    0.078140
2023-02-22   -0.178143
2023-02-23    0.297477
2023-02-24   -1.038518
2023-02-25    0.924399
2023-02-26    0.487757
2023-02-27   -0.611874
2023-02-28    0.791786
2023-03-01    0.791888
Freq: D, dtype: float64


In [ ]:
import pandas as pd
import numpy as np

dictionary  = {'Brand': ['Maruti', 'Renault', 'Hyndai'],
        'Sales': [250, 200, 240]}

df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
